server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/youthcodeman/spring-cloud-learning-config
          username:
          password:

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme


    #非对称加密，需要生成一个整数，keyStore生成
    #加密命令：curl -X POST http://localhost:8080/encrypt -d mmp






