spring:
  application:
    name: microservice-gateway-zuul-fileupload
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000  #在上传大文件的时候，有可能会超时，需要设置hystrix和rubin的超时时间
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

